### ISSUE TITLE
`aliyun.com/gpu-mem` when did you update to nodestatus

### ISSUE THREAD

**Issue by angao** [AliyunContainerService/gpushare-device-plugin#2]
In this repo, I cannot find `aliyun.com/gpu-mem` update to node status, and I just find `aliyun.com/gpu-count` update to node status at `NewNvidiaDevicePlugin` func

**Comment by cheyang** [comment]
`aliyun.com/gpu-mem` is updated by kubelet according to Device plugin mechanism. It reports the info to Kubelet by using 
`Register(kubeletEndpoint, resourceName string)`
